name: Publish to PyPI
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  deploy:
    name: Publish Package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/neopyter
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup JupyterLab Maintainer Tools
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          python_version: "3.11"
          pnpm_version: "10"
          python_package_manager: "uv pip"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "jupyterlab>=4.0.0,<5" hatch jupyter_builder
      - name: Build Distribution
        run: hatch build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
