name: Update Docs
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  update-docs:
    name: Update README and Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1
      - name: Generate Documentation
        run: |
          make document
      - name: Commit and Push Documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto-generate documentation"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
